 insert into ELIGIBILITY_DTLS (ELG_ID,CASE_NO,PLAN_NAME,PLAN_STATUS,BENIFIT_AMT,START_DATE,END_DATE,DENIAL_REASON,HOLDER_NAME,HOLDER_SSN)
 values(1,1111,'SNAP','Approved',100,'2022-05-11','2023-05-11','NA','John',1234);
  insert into ELIGIBILITY_DTLS (ELG_ID,CASE_NO,PLAN_NAME,PLAN_STATUS,BENIFIT_AMT,START_DATE,END_DATE,DENIAL_REASON,HOLDER_NAME,HOLDER_SSN)
 values(2,2222,'SNAP','Denied',00,null,null,'High Income','Roman',1235);
  insert into ELIGIBILITY_DTLS (ELG_ID,CASE_NO,PLAN_NAME,PLAN_STATUS,BENIFIT_AMT,START_DATE,END_DATE,DENIAL_REASON,HOLDER_NAME,HOLDER_SSN)
 values(3,3333,'CCAP','Approved',100,'2022-07-21','2023-07-13','NA','Rock',1236);
  insert into ELIGIBILITY_DTLS (ELG_ID,CASE_NO,PLAN_NAME,PLAN_STATUS,BENIFIT_AMT,START_DATE,END_DATE,DENIAL_REASON,HOLDER_NAME,HOLDER_SSN)
 values(4,4444,'CCAP','Denied',00,null,null,'High Property','Pollard',1237);
  insert into ELIGIBILITY_DTLS (ELG_ID,CASE_NO,PLAN_NAME,PLAN_STATUS,BENIFIT_AMT,START_DATE,END_DATE,DENIAL_REASON,HOLDER_NAME,HOLDER_SSN)
 values(5,5555,'QHP','Approved',100,'2022-09-11','2023-09-12','Adam','John',1238);
  insert into ELIGIBILITY_DTLS (ELG_ID,CASE_NO,PLAN_NAME,PLAN_STATUS,BENIFIT_AMT,START_DATE,END_DATE,DENIAL_REASON,HOLDER_NAME,HOLDER_SSN)
 values(6,6666,'QHP','Denied',00,null,null,'High Rental Income','Sammy',1239);